POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "faaoo@bar.com",
    "password": "dupaadupa1"
}
###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc5NTQ3NTI4fQ.jaHsEbALI1PPL2jXBQvkVm-vyllnLIo6D_v3EdZu4lg


###

GET http://localhost:3000/

###

POST http://localhost:3000/auth/register
Content-type: application/json

{
    "email": "faaoo@bar.com",
    "password": "dupadupa1"
}