POST http://localhost:4000/auth/login
content-type: application/json

{
    "email": "faaaaoo@bar.com",
    "password": "dupadupa1"
}
###

GET http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXItMyIsImlhdCI6MTU3OTU5ODA1Mn0.O-T27iJC7FOd7YiTdjvqknMTor4lGrDC_hZ0mxwUlqY


###

GET http://localhost:4000/

###

POST http://localhost:4000/auth/register
Content-type: application/json

{
    "email": "faaaaoo@bar.com",
    "password": "dupadupa1"
}